-- Disable unused self warnings.
self = false

-- Disable line length limits.
max_line_length = false
max_code_line_length = false
max_string_line_length = false
max_comment_line_length = false

-- Add exceptions for external libraries.
std = "lua51"

globals = {
	-- Clicked
	"Clicked",
	"ClickedMedia",
	"Clique",
	"ClickCastHeader",
	"ClickCastFrames",

	-- WoW API globals
	"StaticPopupDialogs"
}

exclude_files = {
	"**/Libs",
	".luacheckrc",
}

ignore = {
	"542", -- empty if branch
}

read_globals = {
	-- Libraries
	"LibStub",
	"ElvUI",
	"ElvUISpellBookTooltip",
	"WeakAuras",
	"WeakAurasSaved",

	-- WoW API globals
	"AddonCompartmentFrame",
	"AUTOCOMPLETE_DEFAULT_Y_OFFSET",
	"BLUE_FONT_COLOR",
	"BOOKTYPE_PET",
	"BOOKTYPE_PROFESSION",
	"BOOKTYPE_SPELL",
	"CreateFrame",
	"CreateFromMixins",
	"CreateMacro",
	"DisableAddOn",
	"Constants",
	"CopyTable",
	"C_AddOns",
	"C_ChatInfo",
	"C_ClassTalents",
	"C_CreatureInfo",
	"C_Item",
	"C_MountJournal",
	"C_PetJournal",
	"C_PvP",
	"C_SpecializationInfo",
	"C_Spell",
	"C_SpellBook",
	"C_Traits",
	"C_Timer",
	"ClassTalentFrame",
	"ClearCursor",
	"DeleteMacro",
	"EasyMenu",
	"EditMacro",
	"EnableAddOn",
	"Enum",
	"FillLocalizedClassList",
	"FONT_COLOR_CODE_CLOSE",
	"GameFontHighlight",
	"GameFontHighlightLarge",
	"GameFontHighlightSmall",
	"GameMenuFrame",
	"GameTooltip",
	"GetActionInfo",
	"GetActionText",
	"GetActionTexture",
	"GetActiveTalentGroup",
	"GetAddOnEnableState",
	"GetAddOnMetadata",
	"GetBinding",
	"GetBindingKey",
	"GetClassColor",
	"GetCursorInfo",
	"GetCVar",
	"GetFlyoutInfo",
	"GetFlyoutSlotInfo",
	"GetInventoryItemID",
	"GetItemInfo",
	"GetLocale",
	"GetMacroBody",
	"GetMacroIndexByName",
	"GetMacroInfo",
	"GetModifiedClick",
	"GetMouseFoci",
	"GetMouseFocus",
	"GetNumBindings",
	"GetNumGroupMembers",
	"GetNumMacros",
	"GetNumShapeshiftForms",
	"GetNumSpecializations",
	"GetNumSpellTabs",
	"GetNumSubgroupMembers",
	"GetNumTalents",
	"GetNumTalentTabs",
	"GetPetActionInfo",
	"GetPrimaryTalentTree",
	"GetProfessions",
	"GetPvpTalentInfoByID",
	"GetRealmName",
	"GetRealZoneText",
	"GetShapeshiftForm",
	"GetShapeshiftFormInfo",
	"GetSpecialization",
	"GetSpecializationInfo",
	"GetSpecializationInfoByID",
	"GetSpecializationInfoForClassID",
	"GetSpecializationInfoForSpecID",
	"GetSpellBookItemInfo",
	"GetSpellBookItemName",
	"GetSpellInfo",
	"GetSpellSubtext",
	"GetSpellTabInfo",
	"GetTalentTabInfo",
	"GetTalentInfo",
	"GetTalentInfoByID",
	"GetTime",
	"HasPetSpells",
	"HideUIPanel",
	"HIGHLIGHT_FONT_COLOR",
	"hooksecurefunc",
	"InCombatLockdown",
	"InterfaceOptionsFrame",
	"InterfaceOptionsFrame_OpenToCategory",
	"IsAddOnLoaded",
	"IsAltKeyDown",
	"IsControlKeyDown",
	"IsEquippedItem",
	"IsInInstance",
	"IsInRaid",
	"IsLeftShiftKeyDown",
	"IsMacClient",
	"IsMetaKeyDown",
	"IsModifierKeyDown",
	"IsMouseButtonDown",
	"IsPassiveSpell",
	"IsShiftKeyDown",
	"IsSpellKnown",
	"IsSpellKnownOrOverridesKnown",
	"LE_EXPANSION_LEVEL_CURRENT",
	"LE_EXPANSION_BURNING_CRUSADE",
	"LE_EXPANSION_WRATH_OF_THE_LICH_KING",
	"LIGHTBLUE_FONT_COLOR",
	"LoadAddOn",
	"LocalizedClassList",
	"MAX_SPELLS",
	"MAX_NUM_TALENTS",
	"MAX_TALENT_TABS",
	"MAX_TALENT_TIERS",
	"MenuUtil",
	"Mixin",
	"NOT_BOUND",
	"NUM_PET_ACTION_SLOTS",
	"NUM_TALENT_COLUMNS",
	"NORMAL_FONT_COLOR",
	"PanelTemplates_TabResize",
	"PartyFrame",
	"PlayerUtil",
	"PlaySound",
	"RegisterAttributeDriver",
	"RegisterStateDriver",
	"ReloadUI",
	"Round",
	"SecureCmdOptionParse",
	"SetDesaturation",
	"Settings",
	"ShowUIPanel",
	"SpellBookFrame",
	"SpellBookFrame_UpdateSpells",
	"SpellBook_GetSpellBookSlot",
	"SpellButton_OnEnter",
	"SpellButton_OnLeave",
	"SpellButton_UpdateButton",
	"SpellFlyout",
	"SpellFlyoutButton_SetTooltip",
	"StaticPopup_Show",
	"strsplit",
	"SPELLS_PER_PAGE",
	"TalentButtonUtil",
	"TalentUtil",
	"tContains",
	"ToggleDropDownMenu",
	"TooltipDataProcessor",
	"UIDropDownMenu_AddButton",
	"UIDropDownMenu_Initialize",
	"UIParent",
	"UnitClass",
	"UnitGUID",
	"UnitIsDeadOrGhost",
	"UnitIsFriend",
	"UnitIsVisible",
	"UnitLevel",
	"UnitName",
	"UnitRace",
	"WorldFrame",
	"wipe",
	"WOW_PROJECT_BURNING_CRUSADE_CLASSIC",
	"WOW_PROJECT_CLASSIC",
	"WOW_PROJECT_ID",
	"WOW_PROJECT_MAINLINE",
	"WOW_PROJECT_WRATH_CLASSIC",

	-- Lua globals
	"floor",
	"geterrorhandler",
	"error",
	"ipairs",
	"pairs",
	"print",
	"select",
	"setmetatable",
	"string",
	"strlen",
	"strlenutf8",
	"table",
	"tonumber",
	"tostring",
	"type",

	-- Global table
	"_G"
}
